### ISSUE TITLE
Supported languages / Glyph Coverage / Charachter set in METADATA.yml

### ISSUE THREAD

**Issue by pathumego** [raphaelbastide/Unified-Font-Repository#21]
And with this `sample text ` should be also language specific and should be related.

**Comment by pathumego** [comment]
@raphaelbastide @davelab6  Any thoughts :)

**Comment by davelab6** [comment]
Seems better to extract all this from the font itself - the sample text can
be in the NAME table

**Comment by davelab6** [comment]
@raphaelbastide I recommend closing this

**Comment by raphaelbastide** [comment]
> Seems better to extract all this from the font itself - the sample text can be in the NAME table

I agree, this can and should be the case for many other characteristics.
