### ISSUE TITLE
is the misspelling of 'Unfied' on purpose in README.md?

### ISSUE THREAD

**Issue by Moscarda** [raphaelbastide/Unified-Font-Repository#24]
Re: Unfied Typeface Design => Unified Font Repository

**Comment by raphaelbastide** [comment]
No it is not on purpose, but I can’t find this misspelling, can you precise where it is?

**Comment by Moscarda** [comment]
U-N-I-F
not
U-N-F-I

**Comment by raphaelbastide** [comment]
I mean in README.md, where this mistake is located?
